#!/bin/zsh

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

laravelVersion=$(composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1 | cut -d. -f1 | grep -Eo "[0-9]+")

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BBlue}" $NAME "${NC}"

# ----------------------------------------------------------------------------------------
# Laravel Pint
echo "${BBlue}1. Laravel Pint${NC}"
php ./vendor/bin/pint --test

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... laravel pint${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 2. Larastan
echo "${BBlue}2. Larastan${NC}"
php ./vendor/bin/phpstan analyse

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... larastan${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 3. Tests
echo "${BBlue}3. Running Tests${NC}"
php artisan test --parallel

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}3.... tests${NC}"
    exit 1
fi

